### ISSUE TITLE
When changing background colour the display goes crazy.

### ISSUE THREAD

**Issue by Just-another-pleb** [fourstix/Sparkfun_CircuitPython_SerLCD#1]
Just to keep things compartmentalised:

I have updated the *drivers* (libraries?) to the python3.7 version/s.

This is seen in the CLI - note slight difference.
It was only to establish the display is/was working.

```
pi@alarmclock:/usr/local/lib/python3.7/dist-packages$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> import qwiic_serlcd
>>> import time
>>> import sys
>>> myLCD = qwiic_serlcd.QwiicSerlcd()
>>> myLCD.print("Hello")
True
>>> myLCD.setBacklight(150,0,0)
>>> myLCD.setBacklight(80,80,80)
>>> 
pi@alarmclock:/usr/local/lib/python3.7/dist-packages$ 
```

So I tested things were working by *printing* the `Hello`.
Given that worked......

When I put in the `myLCD.setBacklight(150,0,0)`
the display changed colours....  white, green, blue, and many other names were put on the display.

Ironically when done and the screen was RED the letters:  `hell` were visible.
But they were artifacts from the `hello` I had printed.

Still these messages of colour names are flashed on the screen which displaces the cursor while it is trying to print.

Further more it was set to what ever it was.   I sent it to change to 150,0,0 and the display flashed several colours before arriving at the desired colour/setting.

And...  When I did the last line of 80,80,80 to make it basically white again:  The same thing happened.
Many colours are flashed on the screen and vague colour names are printed top left of the screen.

From WHERE are these messages coming?
Is there a way to stop them?

And can the backlight adjustments be done better?

If you want I can make another video showing the screen and what I type all in one, but it will be a very big file at a guess.
I have one (can't remember if I posted it) which is 3.9 Meg big.
It shows the problem clearly.
Alas it is when I was using python 2.7.   And this is to do with 3.7.   The problem is the same.

**Comment by fourstix** [comment]
Hi,
Sorry I didn't see this until now.  For some odd reason GitHub didn't send me any notifications on this project.

Anyway, I believe these messages are coming from the display firmware.  I think there is a way to turn these messages off.  Check out the OpenLCD firmware library at:  https://github.com/sparkfun/OpenLCD

You probably want to use the set_fast_backlight and set_fast_backlight_rgb methods.   The change all the colors at once.
