### ISSUE TITLE
Please publish a release

### ISSUE THREAD

**Issue by raquo** [fourstix/Sparkfun_CircuitPython_SerLCD#10]
Hi @fourstix, thanks for this nice interface!

The latest published release of this library is behind the `master` branch, specifically it does not have the fix allowing people to use this library with CircuitPython (see #3, #4).

Technically people can still use the master branch of this library on CircuitPython by manually copying its `.py` file, but your library is part of [CircuitPython comunity bundle](https://github.com/adafruit/CircuitPython_Community_Bundle) which provides a nicer installation method (with autogenerated `.mpy` files), but that method depends on you publishing the changes as a new version.

If I understand correctly, you need to create and publish a new git tag for the CircuitPython comunity bundle to pick up the new version, and you need to also publish the same version to pypi so that users can install it locally with `pip` for local development and IDE autocomplete support.

I'm very new to CircuitPython so apologies if something here is not 100% correct.

**Comment by fourstix** [comment]
Hi @Raquio,  This code needs refactoring before it can be released.  The last set of Pull Requests made a bit of a mess of things.  I plan to clean up the code soon and do a new release.

**Comment by fourstix** [comment]
I closed the pull request #11 to delete the I2C instance class.  I agree there should be one file, but there still should be support for I2C, SPI and Serial.  And I need to validate that this is all still working.  Maybe it is as simple as deleting the I2C class that Mitago created.  But I need to make sure of that before deleting that class.  I really don't want things to go from bad to worse.

**Comment by raquo** [comment]
Ah, I didn't notice that the `set_i2c_address` method was removed from `sparkfun_serlcd.py`.

For what it's worth, I am currently using the `Sparkfun_SerLCD_I2C` class (from `sparkfun_serlcd.py`), and it seems to work fine (I don't need to set i2c address though).

**Comment by fourstix** [comment]
Ah, that's good news.  Hopefully this will be rather easy to clean up then.  I still wonder if I need to do anything with the parent class once its no longer abstract.

**Comment by raquo** [comment]
It's been ages since I've worked with python, but it looks fine to me. From what I can tell, making the methods non-abstract does not have a practical effect on running the code, it just means that if you decide to implement another subclass of the base class, python won't _force_ you to override / implement those (previously abstract) methods.

All three of the subclasses that you have _already_ override those previously abstract methods – `_write_bytes` and `_change_i2c_address`, so everything should work as-is. And the fact that I'm able to write data to a file using the I2C subclass confirms that, since the `write` method that I'm calling calls `_write_bytes` under the hood.

From what I can tell, the `set_i2c_address` method was only removed due to the desire to factor out the I2C class into a separate file, not because it somehow stopped working due to removing abstract methods (it really shouldn't). So I think adding back that method back where it was will restore the functionality of that method, and keep the library compatible with the previous published version.

**Comment by raquo** [comment]
Longer term, because setting I2C address is only a thing for I2C, I don't think the `set_i2c_address` should be on the base class. You may want to move that method to the I2C subclass, and remove the `_set_i2c_address` method from the base class and the SPI and UART subclasses, since it's not needed there. This is perhaps the kind of refactor that you guys wanted to do originally, but you don't need to commit to all that if you just want to make the `master` work as it used to.

**Comment by fourstix** [comment]
Well, actually..... Setting the I2C address is something one wants available to all children, Serial or SPI.  There isn't much error checking on the I2C address, so one can brick the SerLCD I2C interface by setting it to an invalid address.  

In that case, the easiest way to fix things, is to switch to one of the  communication protocols (SPI or Serial) and then use set_i2c_address to set the address back to something that works. 

That's why set_i2c_address is in the base class, even though (hopefully) one never has to use it in the other child classes.

**Comment by fourstix** [comment]
Created branch b_refactor with last known good version of code.

**Comment by fourstix** [comment]
I've merged a branch and created a release.  It seems like Travis is no longer used any more, so I don't know if the release got published.  But at any rate the code is now refactored and updated.

**Comment by fourstix** [comment]
Created branch b_update_build.  Updated with all the new build files.  Now have a bad build and working to fix issues.

**Comment by fourstix** [comment]
Need to fix code formatting issues with Black in the example files.

**Comment by fourstix** [comment]
Hi @raquio,
Release 1.0.4 of the sparkfun-circuitpython-serlcd package is now available on PyPi!  
Thanks for your help!

**Comment by raquo** [comment]
@fourstix Awesome, thanks! Today I finally switched from my hack to your published version, and it's working fine for me in I2C mode 👍

**Comment by fourstix** [comment]
Great!  I'm glad to hear that.  Thank you for your help!  I really appreciate your feedback.
