### ISSUE TITLE
Remove dependency on ABC

### ISSUE THREAD

**Issue by rsbohn** [fourstix/Sparkfun_CircuitPython_SerLCD#3]
CircuitPython doesn't have PEP-3119 Abstract Base Class available. Would this library work without it?

**Comment by gallaugher** [comment]
I also have this question. Thanks.

**Comment by fourstix** [comment]
Sorry I didn't see this issue until now, GitHub hasn't been alerting me on updates to this project.  
Yes Abstract Base Classes are more of a convenience than anything, and aren't required.  Plus I didn't realize this wasn't supported on CircuitPython, so it's good to remove the ABC dependency.

Fortunately, another user Mitag, forked this code and removed the ABC.   I just merged his changes into the code through a pull request so the ABC dependency should be gone now.
