### ISSUE TITLE
typo in comment in file sparkfun_serlcd.py

### ISSUE THREAD

**Issue by PaulskPt** [fourstix/Sparkfun_CircuitPython_SerLCD#7]
Hi,
First of all: thank you very much for doing this port to CircuitPython! I recently bought two SparkFun SerLCD's. One 16x2 and one 20x4. I had them tested successfully with an Arduino Uno WiFi Rev2. Now I'am about to test them with an Unexpected Maker FeatherS2. So I was studying the files of this repo where I ran across this typo in the file sparkfun_serlcd.py, line 145 where is written "Sprarkfun" instead of "Sparkfun". See the attached screenshot. Now continuing to embed your code into my code.py script for the first test.

![2021-10-08_sparkfun_serlcd py__feedback_typo_](https://user-images.githubusercontent.com/9107950/136554086-5e71372f-033b-4d48-b55b-9e90042d6b94.png)

**Comment by fourstix** [comment]
The last pull request removed the Abstract Base class dependency, which was in Python 3 but wasn't available in CircuitPython.  The comment also needs to remove the works "Abstract base" and just start with "Class" as well as fixing the typo "Sprarkfun".

**Comment by fourstix** [comment]
Fixed in the branch b_refactor
