### ISSUE TITLE
file sparkfun_serlcd.py various errors

### ISSUE THREAD

**Issue by PaulskPt** [fourstix/Sparkfun_CircuitPython_SerLCD#8]
Hi, unfortunately, a use of your sparkfun_serlcd.py module in my test script, running on a UM FeatherS2 (CircuitPython v6.3.0), reported the following errors:
Line 62 - a C-style commenting-out instead of a Python-style ('//' instead '#'). My solution: put a '#' as first character of that line.
Line 445 (and 449) name 'abstractmethod' is not defined. My (test) solution: comment-out the '@abstractmethod' lines;
Line 495 'DEFAULT_I2C_ADDR' is not defined. However, I saw that this definition is present in line 68 but that line has been commented-out ! My solution: take out the '#' at the start of line 68.
Then my script worked OK.
A side note: I used some lines of the example2_backlight.py. (I know this file because I used example 2 the past days for tests with my Arduino Uno WiFi Rev2). Instead of using both: 'import board' and 'import busio', I only did: 'import board', then:
i2c = board.I2C() . According to the CPT docs the initialization of this class looks default for board.SCL and board.SDA. 
That ends my feedback.

![2021-10-08_sparkfun_serlcd py_feedback_nr2](https://user-images.githubusercontent.com/9107950/136596360-fe7e57fa-1977-4234-837a-94fd35feed5e.png)
![2021-10-08_sparkfun_serlcd py_feedback_nr3](https://user-images.githubusercontent.com/9107950/136596484-a7cfefec-c154-495e-b50c-ae695d810b99.png)
![2021-10-08_sparkfun_serlcd py_feedback_nr4](https://user-images.githubusercontent.com/9107950/136596608-5b002828-3f59-446e-9e23-a40fb23e3e74.png)

**Comment by PaulskPt** [comment]
The instantiation of the i2c object:

![2021-10-08_i2c_is_board I2C_](https://user-images.githubusercontent.com/9107950/136597301-26e27cf0-8f18-4223-a20a-7f1ccc1ff4da.png)

**Comment by fourstix** [comment]
Another user submitted a pull request to refactor the library to remove the AbstractBaseClass.  It looks like they made some errors.

Those are reasonable changes to fix the issues.  But I don't have this set up available right now to test it. Do you want to create a Pull Request with these changes?

**Comment by PaulskPt** [comment]
Hi fourstix, thank you for your quick reply!. I can try. I am not so familiar with making PR's. I created a couple of simple repositories myself. But let's try. Give me some time to sort it out.

**Comment by fourstix** [comment]
Hi, @PaulskPt It's fairly easy to do.  Fork the repository, then create a branch for the changes and make and commit your changes to the branch in your fork.  

Once you're happy with the changes in your branch, press the button near the top that says create Pull Request.  It should show your changes to the files, and then click submit to submit the pull request from the branch back to the original repository.

You can sometimes skip creating a branch, but sometimes you get odd things where the commits get out of synch between the two repositories.  With a branch GitHub can keep things in synch.

**Comment by PaulskPt** [comment]
Hi @fourstix, I created a fork and a branche ('branch_psk'); made the changes to sparkfun_serLCD.py and to all the example files. I just created a PR. Greetings.

**Comment by fourstix** [comment]
Fixed with Pull request #9   Thank you @PaulskPt  for fixing this issue!
